spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
        format_sql : true

  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type : trace
